anchor_version = "0.24.2"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = true

[programs.localnet]
# dexloan_listings = "H6FCxCy2KCPJwCoUb9eQCSv41WZBKQaYfB6x5oFajzfj"
dexloan_credit = "gHR5K5YWRDouD6ZiFM3QeGoNYxkLRtvXLpSokk5dxAE"

[programs.devnet]
# dexloan_listings = "H6FCxCy2KCPJwCoUb9eQCSv41WZBKQaYfB6x5oFajzfj"
dexloan_credit = "gHR5K5YWRDouD6ZiFM3QeGoNYxkLRtvXLpSokk5dxAE"

[programs.mainnet]
# dexloan_listings = "H6FCxCy2KCPJwCoUb9eQCSv41WZBKQaYfB6x5oFajzfj"
dexloan_credit = "gHR5K5YWRDouD6ZiFM3QeGoNYxkLRtvXLpSokk5dxAE"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.account]]
address = "Hqxffvgbxfb8iKhyxCvvbdMZ8EEdBjBtsEU8tmYqQdFm"
filename = "./tests/accounts/COLLECTION_MINT.json"

[[test.validator.account]]
address = "8pqrqGekzWdfG1rmqEpNr7WYNKPixFrT6U6Pb7ew5FLs"
filename = "./tests/accounts/COLLECTION_TOKEN_ACCOUNT.json"

[[test.validator.account]]
address = "5jNNGbhKRHbJJzx5MVksXDcBReepsAg1tdXAA16fEH9j"
filename = "./tests/accounts/COLLECTION_METADATA.json"

[[test.validator.account]]
address = "CJAcnATPYjUPzCZmzfksjqkXc13Wdm9Ni2vBbVcL3ttX"
filename = "./tests/accounts/TOKEN_ACCOUNT.json"

[[test.validator.account]]
address = "DTEtZLK8ScwGgjCK8nSbF78gGk6rTWLxkvc4qnYkWijj"
filename = "./tests/accounts/MINT.json"

[[test.validator.account]]
address = "4ndCC5sE947RUoR3xEVwMTFdiRk3MtTK4ADjwZqQKxhw"
filename = "./tests/accounts/METADATA.json"