anchor_version = "0.20.1"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = true

[programs.localnet]
dexloan_listings = "C5dU4Ye5RkHkhdim3mfWLsh8t8i45pRuxMrAWrp5SQZf"

[programs.devnet]
dexloan_listings = "C5dU4Ye5RkHkhdim3mfWLsh8t8i45pRuxMrAWrp5SQZf"

[programs.mainnet]
dexloan_listings = "C5dU4Ye5RkHkhdim3mfWLsh8t8i45pRuxMrAWrp5SQZf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
